# root
root: true

env:
  node: true
  es2020: true

parser: '@typescript-eslint/parser'
plugins: ['@typescript-eslint']

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'

rules:
  #
  'prefer-const': [warn, { 'destructuring': 'all' }]
  'no-constant-condition': off

  # ts
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/no-unused-vars': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-namespace': off
  # '@typescript-eslint/consistent-type-imports': [warn, { 'fixStyle': 'inline-type-imports' }]
  '@typescript-eslint/consistent-type-imports': [warn, { 'fixStyle': 'separate-type-imports' }]
